// Initialize Firebase

// fill the config with the info generated by firebase
var config = {
  apiKey: "AIzaSyDkLcHm1DqMjVNuI08mwUBlwVju971rSu4",
  authDomain: "js-final-99a62.firebaseapp.com",
  databaseURL: "https://js-final-99a62.firebaseio.com",
  projectId: "js-final-99a62",
  storageBucket: "js-final-99a62.appspot.com",
  messagingSenderId: "276255989758"
};
firebase.initializeApp(config);
